//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKGoRehab.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBGoRehabEntities : DbContext
    {
        public DBGoRehabEntities()
            : base("name=DBGoRehabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblEjercicio> tblEjercicio { get; set; }
        public DbSet<tblPaciente> tblPaciente { get; set; }
        public DbSet<tblRutina> tblRutina { get; set; }
        public DbSet<tblTerapeuta> tblTerapeuta { get; set; }
        public DbSet<tblUsuario> tblUsuario { get; set; }
    }
}
