//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKGoRehab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEjercicio
    {
        public tblEjercicio()
        {
            this.tblRutina = new HashSet<tblRutina>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string SeccionCuerpo { get; set; }
        public string URLVideoVimeo { get; set; }
        public string URLImagen { get; set; }
        public Nullable<double> Duracion { get; set; }
        public string Nivel { get; set; }
    
        public virtual ICollection<tblRutina> tblRutina { get; set; }
    }
}
