//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKGoRehab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaciente
    {
        public tblPaciente()
        {
            this.tblRutina = new HashSet<tblRutina>();
        }
    
        public int Id { get; set; }
        public string Estado { get; set; }
        public string Incapacidad { get; set; }
        public Nullable<System.DateTime> FechaUltimoTratamiento { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual ICollection<tblRutina> tblRutina { get; set; }
    }
}
