//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKGoRehab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRutina
    {
        public int Id { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> IdEjercicio { get; set; }
    
        public virtual tblEjercicio tblEjercicio { get; set; }
        public virtual tblPaciente tblPaciente { get; set; }
    }
}
